#!/usr/bin/env python3
"""W12 documentation/spec synchronization helpers."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
ANCHOR_MAP = ROOT / "docs/engineering/spec-anchor-map-v1.md"
ANCHOR_SOURCE_GLOBS = [
    "README.md",
    "sputnik_unified_final_spec.md",
    "docs/engineering/*.md",
    "spec/changelog/*.md",
]
ANCHOR_SOURCE_EXCLUDES = {
    "docs/engineering/spec-anchor-map-v1.md",
}
REGISTRY_GLOBS = [
    "spec/registries/*.yaml",
]
# X-macro mirror of runtime_errors.yaml shared by the VM (kRuntimeErrorNames)
# and the binder (is_native_prelude_name); kept byte-for-byte derivable from the
# registry so error-class names bind identically in both.
RUNTIME_ERRORS_YAML = ROOT / "spec/registries/runtime_errors.yaml"
RUNTIME_ERRORS_DEF = ROOT / "spec/registries/runtime_errors.def"
LINK_SCAN_GLOBS = [
    "README.md",
    "sputnik_unified_final_spec.md",
    "docs/engineering/*.md",
    "spec/changelog/*.md",
]

HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
MARKDOWN_LINK_RE = re.compile(r"(?<!!)\[[^\]]+\]\(([^)]+)\)")
FENCE_RE = re.compile(r"^```")
SPEC_ANCHOR_RE = re.compile(r"^spec_anchor:\s*(\S+)\s*$")
RUNTIME_ERROR_ENTRY_RE = re.compile(r"^\s{2}-\s+name:\s*(.+?)\s*$")
RUNTIME_ERROR_PROPERTY_RE = re.compile(r"^\s{4}(\w+):\s*(.*?)\s*$")


@dataclass(frozen=True)
class Heading:
    path: Path
    line: int
    level: int
    title: str
    anchor: str


@dataclass(frozen=True)
class RuntimeErrorSpec:
    name: str
    parent: str = ""
    fields: tuple[str, ...] = ()
    default_message: str = ""
    default_exit_code: int | None = None


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def table_escape(value: object) -> str:
    return str(value).replace("|", r"\|").replace("\n", " ")


def source_files(patterns: Iterable[str], excludes: set[str] | None = None) -> list[Path]:
    excludes = excludes or set()
    files: list[Path] = []
    seen: set[str] = set()
    for pattern in patterns:
        for path in sorted(ROOT.glob(pattern)):
            if not path.is_file():
                continue
            relative = rel(path)
            if relative in excludes or relative in seen:
                continue
            files.append(path)
            seen.add(relative)
    return files


def strip_inline_markup(title: str) -> str:
    title = re.sub(r"<[^>]+>", "", title)
    title = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", title)
    return title.replace("`", "").replace("*", "").replace("_", "").strip()


def anchor_base(title: str) -> str:
    normalized = strip_inline_markup(title).lower()
    chars: list[str] = []
    for char in normalized:
        if char.isalnum() or char in {" ", "-", "_"}:
            chars.append(char)
        elif char.isspace():
            chars.append(" ")
    slug = re.sub(r"\s+", "-", "".join(chars).strip())
    slug = re.sub(r"-+", "-", slug)
    return slug or "section"


def headings_for(path: Path, emit_level: int = 2) -> list[Heading]:
    headings: list[Heading] = []
    used: dict[str, int] = {}
    in_fence = False
    for index, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = HEADING_RE.match(line)
        if not match:
            continue
        level = len(match.group(1))
        title = match.group(2).strip()
        base = anchor_base(title)
        previous = used.get(base, 0)
        used[base] = previous + 1
        anchor = base if previous == 0 else f"{base}-{previous}"
        if level <= emit_level:
            headings.append(Heading(path, index, level, title, anchor))
    return headings


def anchor_index() -> dict[str, set[str]]:
    index: dict[str, set[str]] = {}
    for path in source_files(ANCHOR_SOURCE_GLOBS):
        anchors = {heading.anchor for heading in headings_for(path, emit_level=6)}
        index[rel(path)] = anchors
    return index


def registry_rows() -> list[tuple[str, int, str]]:
    rows: list[tuple[str, int, str]] = []
    for path in source_files(REGISTRY_GLOBS):
        data = path.read_bytes()
        lines = path.read_text(encoding="utf-8").count("\n")
        rows.append((rel(path), lines, hashlib.sha256(data).hexdigest()))
    return rows


def generate_anchor_map() -> str:
    markdown: list[str] = [
        "# sputnik.spec-anchor-map.v1",
        "",
        "Status: generated W12 anchor map for the current repository docs/spec set.",
        "",
        "Generated by `python3 tools/spec_sync.py anchor-map`.",
        "Check with `make spec-sync-check`.",
        "",
        "## Source Set",
        "",
        "| Source | Included headings |",
        "| --- | ---: |",
    ]

    sources = source_files(ANCHOR_SOURCE_GLOBS, ANCHOR_SOURCE_EXCLUDES)
    all_headings: list[Heading] = []
    for path in sources:
        headings = headings_for(path, emit_level=2)
        all_headings.extend(headings)
        markdown.append(f"| `{table_escape(rel(path))}` | {len(headings)} |")

    markdown.extend(
        [
            "",
            "## Registry Inventory",
            "",
            "| Registry | Lines | SHA-256 |",
            "| --- | ---: | --- |",
        ]
    )
    for path, lines, digest in registry_rows():
        markdown.append(f"| `{table_escape(path)}` | {lines} | `{digest}` |")

    markdown.extend(
        [
            "",
            "## Anchor Map",
            "",
            "| Source | Line | Level | Anchor | Heading |",
            "| --- | ---: | ---: | --- | --- |",
        ]
    )
    for heading in all_headings:
        path = rel(heading.path)
        link = f"../../{path}#{heading.anchor}"
        source_link = f"[`{table_escape(path)}`](../../{path})"
        anchor_link = f"[`{table_escape(heading.anchor)}`]({link})"
        markdown.append(
            "| "
            + f"{source_link} | {heading.line} | {heading.level} | "
            + f"{anchor_link} | {table_escape(heading.title)} |"
        )

    markdown.append("")
    return "\n".join(markdown)


def strip_fenced_code(markdown: str) -> str:
    kept: list[str] = []
    in_fence = False
    for line in markdown.splitlines():
        if FENCE_RE.match(line):
            in_fence = not in_fence
            kept.append("")
            continue
        kept.append("" if in_fence else line)
    return "\n".join(kept)


def strip_line_suffix(path: Path) -> Path:
    text = str(path)
    match = re.match(r"^(.*):(\d+)$", text)
    if match and not path.exists():
        return Path(match.group(1))
    return path


def resolve_link(source: Path, target: str) -> tuple[Path | None, str | None]:
    target = target.strip()
    if target.startswith("<") and target.endswith(">"):
        target = target[1:-1]
    target = target.split(" ", 1)[0]
    if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", target):
        return None, None
    path_part, _, anchor = target.partition("#")
    if not path_part:
        return source, anchor or None
    if path_part.startswith("/"):
        path = Path(path_part)
    else:
        path = (source.parent / path_part).resolve()
    return strip_line_suffix(path), anchor or None


def check_links() -> list[str]:
    errors: list[str] = []
    anchors = anchor_index()
    for source in source_files(LINK_SCAN_GLOBS):
        text = strip_fenced_code(source.read_text(encoding="utf-8"))
        for target in MARKDOWN_LINK_RE.findall(text):
            resolved, anchor = resolve_link(source, target)
            if resolved is None:
                continue
            if not resolved.exists():
                errors.append(f"{rel(source)}: missing link target {target}")
                continue
            try:
                resolved_rel = rel(resolved)
            except ValueError:
                continue
            if anchor and resolved.suffix.lower() in {".md", ".markdown"}:
                available = anchors.get(resolved_rel)
                if available is not None and anchor not in available:
                    errors.append(
                        f"{rel(source)}: missing anchor #{anchor} in {resolved_rel}"
                    )
    return errors


def check_registry_anchors() -> list[str]:
    errors: list[str] = []
    for registry in source_files(REGISTRY_GLOBS):
        for index, line in enumerate(registry.read_text(encoding="utf-8").splitlines(), 1):
            match = SPEC_ANCHOR_RE.match(line)
            if not match:
                continue
            target = match.group(1)
            candidates = [ROOT / target, ROOT / "spec_history" / target]
            if not any(candidate.exists() for candidate in candidates):
                errors.append(f"{rel(registry)}:{index}: stale spec_anchor {target}")
    return errors


def parse_yaml_scalar(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        if value[0] == '"':
            return str(json.loads(value))
        return value[1:-1].replace("''", "'")
    return value


def parse_inline_yaml_list(value: str) -> tuple[str, ...]:
    value = value.strip()
    if not value.startswith("[") or not value.endswith("]"):
        raise ValueError(f"expected inline YAML list, got {value!r}")
    body = value[1:-1].strip()
    if not body:
        return ()
    return tuple(parse_yaml_scalar(item) for item in body.split(","))


def runtime_error_yaml_specs() -> list[RuntimeErrorSpec]:
    specs: list[RuntimeErrorSpec] = []
    in_errors = False
    current: dict[str, object] | None = None
    for line in RUNTIME_ERRORS_YAML.read_text(encoding="utf-8").splitlines():
        if line.rstrip() == "errors:":
            in_errors = True
            continue
        if not in_errors:
            continue
        entry = RUNTIME_ERROR_ENTRY_RE.match(line)
        if entry:
            if current is not None:
                specs.append(RuntimeErrorSpec(**current))
            current = {"name": parse_yaml_scalar(entry.group(1))}
            continue
        prop = RUNTIME_ERROR_PROPERTY_RE.match(line)
        if prop and current is not None:
            key, raw = prop.groups()
            if key == "fields":
                current[key] = parse_inline_yaml_list(raw)
            elif key == "default_exit_code":
                current[key] = int(raw)
            elif key in {"parent", "default_message"}:
                current[key] = parse_yaml_scalar(raw)
            else:
                raise ValueError(f"unknown runtime error property {key!r}")
            continue
        if line.strip() and not line.startswith((" ", "\t")):
            break
        if line.strip():
            raise ValueError(f"invalid runtime error registry line: {line}")
    if current is not None:
        specs.append(RuntimeErrorSpec(**current))
    return specs


RUNTIME_ERROR_FIELD_BITS = {
    "option": 1 << 0,
    "value": 1 << 1,
    "exit_code": 1 << 2,
    "usage": 1 << 3,
    "help": 1 << 4,
}


def validate_runtime_error_specs(specs: list[RuntimeErrorSpec]) -> list[str]:
    errors: list[str] = []
    by_name = {spec.name: spec for spec in specs}
    if len(by_name) != len(specs):
        errors.append("runtime error registry contains duplicate names")
    for spec in specs:
        if spec.parent and spec.parent not in by_name:
            errors.append(f"{spec.name}: unknown parent {spec.parent}")
        unknown_fields = sorted(set(spec.fields) - RUNTIME_ERROR_FIELD_BITS.keys())
        if unknown_fields:
            errors.append(f"{spec.name}: unknown fields {unknown_fields}")
        if spec.default_exit_code is not None and "exit_code" not in spec.fields:
            errors.append(
                f"{spec.name}: default_exit_code requires the exit_code field"
            )
        seen: set[str] = set()
        current = spec
        while current.parent:
            if current.name in seen:
                errors.append(f"{spec.name}: cycle in runtime error ancestry")
                break
            seen.add(current.name)
            parent = by_name.get(current.parent)
            if parent is None:
                break
            current = parent
    return errors


def generate_runtime_error_def() -> str:
    specs = runtime_error_yaml_specs()
    validation_errors = validate_runtime_error_specs(specs)
    if validation_errors:
        raise ValueError("; ".join(validation_errors))
    lines = [
        "// Generated from spec/registries/runtime_errors.yaml.",
        "// Consumed by runtime/vm.cpp and frontend/binder/binder.cpp.",
        "// Define SPUTNIK_RUNTIME_ERROR(name, parent, default_message,",
        "// default_exit_code, field_mask) before including.",
    ]
    for spec in specs:
        field_mask = 0
        for field in spec.fields:
            field_mask |= RUNTIME_ERROR_FIELD_BITS[field]
        default_exit_code = (
            spec.default_exit_code if spec.default_exit_code is not None else -1
        )
        lines.append(
            "SPUTNIK_RUNTIME_ERROR("
            + ", ".join(
                [
                    json.dumps(spec.name),
                    json.dumps(spec.parent),
                    json.dumps(spec.default_message),
                    str(default_exit_code),
                    str(field_mask),
                ]
            )
            + ")"
        )
    lines.append("")
    return "\n".join(lines)


def check_runtime_error_def() -> list[str]:
    if not RUNTIME_ERRORS_DEF.exists():
        return [f"missing generated mirror: {rel(RUNTIME_ERRORS_DEF)}"]
    try:
        expected = generate_runtime_error_def()
    except ValueError as error:
        return [f"{rel(RUNTIME_ERRORS_YAML)}: {error}"]
    actual = RUNTIME_ERRORS_DEF.read_text(encoding="utf-8")
    if actual != expected:
        return [
            f"{rel(RUNTIME_ERRORS_DEF)}: out of sync with "
            f"{rel(RUNTIME_ERRORS_YAML)}; run "
            "`python3 tools/spec_sync.py runtime-errors-def > "
            "spec/registries/runtime_errors.def`"
        ]
    return []


def cmd_anchor_map(_: argparse.Namespace) -> int:
    sys.stdout.write(generate_anchor_map())
    return 0


def cmd_runtime_errors_def(_: argparse.Namespace) -> int:
    try:
        sys.stdout.write(generate_runtime_error_def())
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    return 0


def cmd_check(_: argparse.Namespace) -> int:
    errors: list[str] = []
    expected = generate_anchor_map()
    if not ANCHOR_MAP.exists():
        errors.append(f"missing generated anchor map: {rel(ANCHOR_MAP)}")
    elif ANCHOR_MAP.read_text(encoding="utf-8") != expected:
        errors.append(
            "generated anchor map is stale; run "
            "`python3 tools/spec_sync.py anchor-map > docs/engineering/spec-anchor-map-v1.md`"
        )
    errors.extend(check_links())
    errors.extend(check_registry_anchors())
    errors.extend(check_runtime_error_def())
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    print("spec sync docs are current")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    anchor_parser = subparsers.add_parser("anchor-map")
    anchor_parser.set_defaults(func=cmd_anchor_map)
    runtime_errors_parser = subparsers.add_parser("runtime-errors-def")
    runtime_errors_parser.set_defaults(func=cmd_runtime_errors_def)
    check_parser = subparsers.add_parser("check")
    check_parser.set_defaults(func=cmd_check)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
